Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using CSharpbelt.Models;
using System.Linq;
using Microsoft.AspNetCore.Identity;

namespace CSharpbelt.Controllers
{
    public class ActivityController : Controller
    {
        private AshContext mycontext;

        // this is to get the user who is currently active
        private User ActiveUser
        {
            get {return mycontext.Users.Where(u => u.UserId ==HttpContext.Session.GetInt32("id")).FirstOrDefault();}
        }
        public ActivityController(AshContext context)
        {
            mycontext = context;
        }
        [HttpGet]
        [Route("Dashboard")]
        public IActionResult Index()
        {
            if(HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToAction("Index", "User");
            }
            return View(InitializeDashboard());
        }
        [HttpGet]
        [Route("NewActivity")]
        public IActionResult NewActivity()
        {
            if(HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToAction("Index", "User");
            }
            return View();
        }

        [HttpPost]
        [Route("AddActivity")]
        public IActionResult AddActivity(NewActivity newActivity)
        {
            // Console.WriteLine("lollll");
            if(HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToAction("Index", "User");
            }

    // part 1 begin
            var ParticipatingActivities = mycontext.Participate.Where( p => p.UserId == ActiveUser.UserId).Select(u => u.ParticipatingActivities).ToList();
            foreach (var activity in ParticipatingActivities)
            {
                Console.WriteLine(activity.Date);
                DateTime start_date = activity.Date;
                DateTime end_date = start_date.AddMinutes((double)activity.Duration);
                Console.WriteLine(end_date);
                DateTime activity_date = newActivity.Date;
                DateTime activity_end_date = activity_date.AddMinutes((double)newActivity.Duration);
            }
            var CreatedActivities = mycontext.Activities.Where(u => u.UserId == ActiveUser.UserId).Include( a => a.Coordinator).ToList();
            foreach(var activity in CreatedActivities)
            {
                DateTime start_date = activity.Date;
                DateTime end_date = start_date.AddMinutes((double)activity.Duration);
                Console.WriteLine(end_date);
                DateTime activity_date = newActivity.Date;
                DateTime activity_end_date = activity_date.AddMinutes((double)newActivity.Duration);
            }
            if(Request.Form["dur"] == "minutes")
            {
                newActivity.Duration =  newActivity.Duration;
            }
            if(Request.Form["dur"] == "hours")
            {
                newActivity.Duration =  newActivity.Duration * 60;
            }
            if(Request.Form["dur"] == "days")
            {
                newActivity.Duration =  newActivity.Duration * 1440;
            }
    // // end part 1

            if(ModelState.IsValid)
            {
                Activity theActivity = new Activity()
                {
                    Title = newActivity.Title,
                    Date = newActivity.Date,
                    Time = newActivity.Time,
                    Duration = newActivity.Duration,
                    Description = newActivity.Description,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    UserId = ActiveUser.UserId,
                };
                mycontext.Add(theActivity);
                mycontext.SaveChanges();
                Activity currentActivity = mycontext.Activities.Where(a => a.UserId == ActiveUser.UserId).Last();
                int currentActivityId = currentActivity.ActivityId;
                return Redirect($"ActivityDetails/{currentActivityId}");
            }
            return View("NewActivity");
        }


        [HttpGet]
        [Route("Join/{activity_id}")]
        public IActionResult JoinActivity(int activity_id)
        {
             if(HttpContext.Session.GetInt32("id") == null)
            {
                return RedirectToAction("Index", "User");
            }
    // insert part 2 here
    //not able to joy the overlap activities
            var ParticipatingActivities = mycontext.Participate.Where( p => p.UserId == ActiveUser.UserId).Select(u => u.ParticipatingActivities).ToList();
            Activity currentActivity = mycontext.Activities.SingleOrDefault(a => a.ActivityId == activity_id);
            foreach (var activity in ParticipatingActivities)
            {
                DateTime start_date = activity.Date;
                DateTime end_date = start_date.AddMinutes((double)activity.Duration);
                Console.WriteLine(end_date);
                System.Console.WriteLine("Is this getting joined or not #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$");
                DateTime activity_date = currentActivity.Date;
                DateTime activity_end_date = activity_date.AddMinutes((double)currentActivity.Duration);
                if(activity_date < start_date && activity_end_date < start_date)
                {
                    currentActivity.Date = currentActivity.Date;
                    currentActivity.Duration = currentActivity.Duration;
                }
                else if (activity_date > start_date && activity_date > end_date )
                {
                    currentActivity.Date = currentActivity.Date;
                    currentActivity.Duration = currentActivity.Duration;
                }
                else
                {
                    ViewBag.Error = null;
                    TempData["error"] = "Activity Conflict!!!!! You cannot be at 2 places at once";
                    Console.WriteLine("Dashboard");
                    return Redirect ("/Dashboard");
                }
            }
    // end part 2 

            Participate newParticipation = new Participate
            {
                UserId = ActiveUser.UserId,
                ActivityId = activity_id
            };
            mycontext.Participate.Add(newParticipation);
            mycontext.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        [Route("Leave/{activity_id}")]
        public IActionResult LeaveActivity(int activity_id)
        {
            Participate currentParticipate = mycontext.Participate.SingleOrDefault( p => p.UserId == ActiveUser.UserId && p.ActivityId == activity_id);
            mycontext.Participate.Remove(currentParticipate);
            mycontext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Route("Delete/{activity_id}")]
        public IActionResult DeleteActivity(int activity_id)
        {
            Activity theActivity = mycontext.Activities.SingleOrDefault(a => a.ActivityId == activity_id);
            mycontext.Activities.Remove(theActivity);
            mycontext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Route("ActivityDetails/{activity_id}")]
        public IActionResult ActivityDetails( int activity_id)
        {
            Activity theActivity = mycontext.Activities.Include(a => a.Participants).ThenInclude(p => p.ParticipatingUsers).SingleOrDefault(a => a.ActivityId == activity_id);
            int num = theActivity.UserId;
            ViewBag.theUser = mycontext.Users.SingleOrDefault( u => u.UserId == num);
            ViewBag.ActiveUserId = ActiveUser.UserId;
            return View(theActivity);
        }
        public DashboardModels InitializeDashboard()
        {
            var ParticipatingActivities = mycontext.Participate.Where( p => p.UserId == ActiveUser.UserId).Select(u => u.ParticipatingActivities).ToList();
            return new DashboardModels
            {
                AllActivities = mycontext.Activities.OrderBy(u => u.Date).Include( a => a.Participants).ThenInclude(p => p.ParticipatingUsers).ToList(),
                AllUsers = mycontext.Users.Include( u => u.CreatedActivities).ToList(),
                User = ActiveUser,
                JoinedActivities = ParticipatingActivities       
            };
        }
    }
}

Views/Activity/ActivityDetails.cshtml
@{
    ViewData["Title"] = "Activity Dashboard";
}
@model CSharpbelt.Models.Activity
@using CSharpbelt.Models
@using System.Linq
<div class="header">
    <h1>Dojo Activity Center</h1>
    <a id="home" href="/Dashboard">Activity Dashboard</a>
</div>
<div id="heading">
<h2>Name of the Activity is: @Model.Title</h2>
    @if(ViewBag.ActiveUserId == Model.UserId)
    {
        <a href="/Delete/@Model.ActivityId"><button class="btn btn-primary theButton">Delete</button></a>
    }
    else
    {
        @if(Model.Participants.Where(p => p.UserId == ViewBag.ActiveUserId).Count() == 0)
            {
                <a href="/Join/@Model.ActivityId"><button class="btn btn-primary theButton">JOIN Me!! :-) </button></a>
            }
            else
            {
                <a href="/Leave/@Model.ActivityId"><button class="btn btn-primary theButton">Leave Me!!  :-( </button></a>
            }
    }

</div>
<div class="theSections">
<h3>Activity Arranged By: @ViewBag.theUser.FirstName</h3>
</div>
<div class="theSections">
<h3>Description about this Activity :</h3>
<div id="theDescription">
    @Model.Description
</div>
</div>
<div class="theSections">
<h3>Participants:</h3>
<ul>
@foreach(var participant in Model.Participants)
{
    <li> <h4>Mr/Ms:  @participant.ParticipatingUsers.FirstName @participant.ParticipatingUsers.LastName </h4></li>
}
</ul>
</div>

Views/Activity/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
@model CSharpbelt.Models.DashboardModels
@using CSharpbelt.Models
@using System.Linq

<div class="header">
    <h1>Welcome (@Model.User.FirstName) to Dojo Activity Center</h1>
    <h4>Here you can add an activity or join other user's activity</h4>
    <a id="logout" href="Logout">Log Off</a>
</div>
@if (ViewBag.Error == null)
{
    @TempData["error"]
}
<table class="table">
    <tr>
        <td><h5>Name of the Activity/(click to check the details)</h5></td>
        <td><h5>Date and Time</h5></td>
        <td><h5>Duration</h5></td>
        <td><h5>Event Coordinator</h5></td>
        <td><h5>No. of Participantsd</h5></td>
        <td><h5>Your Choices</h5></td>
    </tr>
    @foreach (var activity in Model.AllActivities)
    {
        <tr>
            <td><a href="ActivityDetails/@activity.ActivityId">@activity.Title</a></td>
            <td>@activity.Date.ToString("MM/dd") @@ @activity.Time</td>
            @if(activity.Duration <= 60)
            {
                <td>@activity.Duration Minutes</td>
            }
            else if(activity.Duration <= 1440)
            {
                int duration = activity.Duration/60;
                <td>@duration Hour(s)</td>
            }
            else
            {
                int duration = activity.Duration/1440;
                <td>@duration Day(s)</td>
            }
            @{
                User theUser = (Model.AllUsers.Where(u => u.UserId == activity.UserId)).SingleOrDefault();
                <td>@theUser.FirstName</td>
            }
            <td>@activity.Participants.Count</td>
            @if(Model.User.UserId == activity.UserId)
            {
                <td><a href="Delete/@activity.ActivityId">Delete</a></td>
            }
            else
            {
                if(activity.Participants.Where(p => p.UserId == Model.User.UserId).Count() == 0)
                {
                    <td><a href="Join/@activity.ActivityId">Join</a></td>
                }
                else
                {
                    <td><a href="Leave/@activity.ActivityId">Leave</a></td>
                }
            }
        </tr>
    }
</table>
<a href="NewActivity"><button class="btn btn-primary">Create another !!!</button></a>

Views/Activity/NewActivity.cshtml
@{
    ViewData["Title"] = "New Activity Page";
}
@model CSharpbelt.Models.NewActivity
<div class="header">
    <h1>Dojo Activity Center</h1>
    <a id="home" href="/Dashboard">Home/Back</a>
    <a id="logout" href="Logout">Log Off</a>
</div>
<h2>Create an Activity!</h2>
<form asp-action="AddActivity" asp-controller="Activity" method="post">
    <div class="form-group">
        <span asp-validation-for="Title"></span>
        <label asp-for="Title"></label>
        <input asp-for="Title" >
    </div>
    <div class="form-group">
        <span asp-validation-for="Date"></span>
        <label asp-for="Date"></label>
        <input type="date" asp-for="Date">
    </div>
    <div class="form-group">
        <span asp-validation-for="Time"></span>
        <label asp-for="Time"></label>
        <input placeholder="for example 9:30 AM" asp-for="Time">
    </div>
    <div class="form-group">
        <span asp-validation-for="Duration"></span>
        <label asp-for="Duration"></label>
        <input type="number" asp-for="Duration">
        <select name="dur">
            <option value="minutes">Minutes</option>
            <option value="hours">Hours</option>
            <option value="days">Days</option>
        </select>
    </div>
    <div class="form-group">
        <span asp-validation-for="Description"></span>
        <label asp-for="Description"></label>
        <textarea class="form-control" asp-for="Description" cols="30" rows="10"></textarea>
    </div>
    <input type="submit" class="button-primary" value="Create Activity">
</form>